on:
  pull_request

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache service entrypoint
        uses: actions/cache@v2
        with:
          path: |
            pyzetasql/server/service
          key: ${{ runner.os }}-${{ hashFiles('zetasql') }}-${{ matrix.python-version }}

      - name: Cache proto files
        uses: actions/cache@v2
        with:
          path: |
            pyzetasql/proto/zetasql
          key: ${{ runner.os }}-${{ hashFiles('zetasql') }}-${{ matrix.python-version }}

      - name: Setup Android SDK
        run: echo "y" | /usr/local/lib/android/sdk/tools/bin/sdkmanager --uninstall "build-tools;29.0.2"

      - name: Install poetry
        run: pip install poetry

      - name: Build
        run: poetry install

      - name: Test
        run: poetry run pytest test